eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/
server:
  port: 9411
spring:
  application:
    name: zipkin-server
  rabbitmq:
    host: 192.168.33.82
    port: 5672
    username: admin
    password: admin

zipkin:
  storage:
    type: elasticsearch
    StorageComponent: elasticsearch
    elasticsearch:
      cluster: yanggy
      max-requests: 30
      index: zipkin-trace
      index-shards: 5
      index-replicas: 1
      hosts: localhost:9200

